services:
  - type: web
    name: sakura-xyz
    env: node
    plan: free
    buildCommand: npm install && npm run build-css
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: FIREBASE_PROJECT_ID
        value: sakura-auth-66415
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
